apiVersion: v1
kind: ConfigMap
metadata:
  name: service-cm-{{ include "chemistry-pack.fullname" . }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
data:
  rsyslog: |
    #!/command/execlineb -P
    rsyslogd