apiVersion: v1
kind: ConfigMap
metadata:
  name: script-cm-{{ include "chemistry-pack.fullname" . }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
data:
  setup.sh: |
    #!/bin/bash
    echo "Hello, World!"