apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-cm-{{ include "chemistry-pack.fullname" . }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
data:
  CUSTOM_PORT: "8080"
  START_DOCKER: "false"
  CUSTOM_USER: {{ .Values.settings.user }}
  PASSWORD: {{ .Values.settings.password }}
  {{- with .Values.envs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
