{{- $gpuKEY := "nvidia.com/gpu" -}}
{{- $encoder := "x264enc" -}}
{{- if or (and (hasKey .Values.resources "requests") (hasKey .Values.resources.requests $gpuKEY)) (and (hasKey .Values.resources "limits") (hasKey .Values.resources.limits $gpuKEY)) }}
{{- $encoder = "nvh264enc" -}}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-cm-{{ include "chemistry-pack.fullname" . }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
data:
  SELKIES_BASIC_AUTH_USER: {{ .Values.settings.user }}
  SELKIES_BASIC_AUTH_PASSWORD: {{ .Values.settings.password }}
  TZ: "UTC"
  DISPLAY_SIZEW: "1920"
  DISPLAY_SIZEH: "1080"
  DISPLAY_REFRESH: "60"
  DISPLAY_DPI: "96"
  DISPLAY_CDEPTH: "24"
  KASMVNC_ENABLE: {{ quote .Values.settings.kasm }}
  SELKIES_ENCODER: {{ .Values.settings.encoder | default $encoder | quote }}
  SELKIES_ENABLE_RESIZE: "false"
  SELKIES_VIDEO_BITRATE: "8000"
  SELKIES_FRAMERATE: "60"
  SELKIES_AUDIO_BITRATE: "128000"
  SELKIES_ENABLE_BASIC_AUTH: "true"
  SELKIES_ENABLE_HTTPS: "false"
  {{- if not .Values.settings.kasm }}
  SELKIES_TURN_HOST: "192.168.0.141"
  SELKIES_TURN_PORT: "3478"
  SELKIES_TURN_PROTOCOL: "udp"
  SELKIES_TURN_TLS: "false"
  TURN_MIN_PORT: "65534"
  TURN_MAX_PORT: "65535"
  {{- end }}