{{- $ingressPATH := (index (index .Values.ingress.hosts 0).paths 0).path -}}
{{- $gpuKEY := "nvidia.com/gpu" -}}
{{- $encoder := "x264enc" -}}
{{- if or (and (hasKey .Values.resources "requests") (hasKey .Values.resources.requests $gpuKEY)) (and (hasKey .Values.resources "limits") (hasKey .Values.resources.limits $gpuKEY)) }}
Hello: world
{{- $encoder = .Values.setting.encoder | default "nvh264enc" -}}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chemistry-pack.fullname" . }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "chemistry-pack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chemistry-pack.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ $ingressPATH }}
              port: http
              httpHeaders:
              - name: Authorization
                value: Basic {{ printf "%s:%s" .Values.settings.user .Values.settings.password  | b64enc }}
          readinessProbe:
            httpGet:
              path: {{ $ingressPATH }}
              port: http
              httpHeaders:
              - name: Authorization
                value: Basic {{ printf "%s:%s" .Values.settings.user .Values.settings.password  | b64enc }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: TZ
            value: "UTC"
          - name: DISPLAY_SIZEW
            value: "1920"
          - name: DISPLAY_SIZEH
            value: "1080"
          - name: DISPLAY_REFRESH
            value: "60"
          - name: DISPLAY_DPI
            value: "96"
          - name: DISPLAY_CDEPTH
            value: "24"
          - name: KASMVNC_ENABLE
            value: {{ quote .Values.settings.kasm }}
          - name: SELKIES_ENCODER
            value: {{ quote $encoder }}
          - name: SELKIES_ENABLE_RESIZE
            value: "false"
          - name: SELKIES_VIDEO_BITRATE
            value: "8000"
          - name: SELKIES_FRAMERATE
            value: "60"
          - name: SELKIES_AUDIO_BITRATE
            value: "128000"
          - name: SELKIES_ENABLE_BASIC_AUTH
            value: "true"
          - name: SELKIES_ENABLE_HTTPS
            value: "false"
          stdin: true
          tty: true
          envFrom:
          - configMapRef:
              name: environment-cm-{{ include "chemistry-pack.fullname" . }}
          volumeMounts:
          - mountPath: "/home/ubuntu"
            name: data-storage
          - mountPath: /cache
            name: cache-vol
          - mountPath: /dev/shm
            name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: "Memory"
          sizeLimit: 4Gi
      - name: cache-vol
        persistentVolumeClaim:
          claimName: cache-pvc-{{ include "chemistry-pack.fullname" . }}
      - name: data-storage
        persistentVolumeClaim:
          claimName: pvc-{{ include "chemistry-pack.fullname" . }}
      # - name: service-config
      #   configMap:
      #     name: service-cm-{{ include "chemistry-pack.fullname" . }}
      #     defaultMode: 0777
      - name: script-config
        configMap:
          name: script-cm-{{ include "chemistry-pack.fullname" . }}
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
