apiVersion: v1
kind: Service
metadata:
  name: {{ include "chemistry-pack.fullname" . }}
  {{- if not .Values.settings.kasm }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.settings.ip }}
  {{- end }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if not .Values.settings.kasm }}
    - port: 3478
      protocol: UDP
      targetPort: turn
      name: turn
    - port: 65534
      protocol: UDP
      targetPort: turn-a
      name: turn-a
    - port: 65535
      protocol: UDP
      targetPort: turn-b
      name: turn-b
    {{- end }}
  selector:
    {{- include "chemistry-pack.selectorLabels" . | nindent 4 }}
